- README.md
- oauth2/wrike_connector.rb
https://github.com/workato/workato/issues/13606
> Wrike connector

- README.md
- custom_auth/knack_hq_connector.rb
https://github.com/workato/workato/issues/13987
> Knack HQ custom adapter

- README.md
- basic_auth/watson_tone_analyzer_connector.rb
IBM Watson (cloud-based Artificial Intelligence) Tone Analyzer
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/tone-analyzer/api/v3/#post-tone
> watson tone analyzer

- basic_auth/close_io_connector.rb
- custom_auth/safetyculture_connector.rb
- oauth2/accelo_connector.rb
https://github.com/workato/workato/issues/13473
> Add desc trigger to sample custom adapters

- README.md
- custom_auth/neto_connector.rb
https://www.neto.com.au/api/customers/getcustomer/
> Neto connector

- README.md
- oauth2/amcards_connector.rb
Please make this connector available to all users.
> Added a new connector file for AMcards.com.

- custom_auth/infobip_connector.rb
I've added a connector for Infobip's sms platform.
It exposes one trigger and one action.
The trigger will fetch text messages that the client has received on one of her registered phone numbers.
The action will simply send an sms text message.
> Added infobip connector

- .hound.yml
- .rubocop.yml
- README.md
- custom_auth/tsheets_connector.rb
- Adds Query Timesheets action to TSheets
> Added TSheets adapter

- api_key_auth/salesforceiq.rb
- api_key_auth/workfront.rb
- oauth2/sharepoint.rb
> Adapters Review

- custom_auth/bill__connector.rb
- custom_auth/bill_connector.rb
- custom_auth
_______
- New/updated vendor
- New or updated vendor in bill.com
_______
-   
_______
**CS-Contact:** @vivek88
**Issue link:** [workato/issues/issues/4745](https://github.com/workato/issues/issues/4745)
> Bill.com SDK adapter

- oauth2/nationbuilder_connector.rb
- Oauth2
_______
_______
_______
**CS-Contact:** 
**Issue link:**  https://github.com/workato/issues/issues/4899
> NationBuilder (custom) - SDK adapter

- api_key_auth/Calendly.rb
> Calendly SDK Connector

- oauth2/Typeform.rb
Changed authentication to oauth2. Updated trigger and action.
Triggers:
Actions:
> Typeform Connector SDK

- custom_auth/bmc_innovation_suite_connector.rb
- custom_auth
_______
_______
_______
**CS-Contact:**  @vivek88
**Issue link:**  NA
> BMC Innovation Suite - SDK adapter

- api_key_auth/facebook_connector.rb
- api_key_auth
_______
_______
_______
**CS-Contact:**  @allanteng, @alvinee
**Issue link:**  NA
> Facebook (custom) - SDK adapter

- api_key_auth/action_network_connector.rb
- api_key_auth
_______
_______
**CS-Contact:**  -
**Issue link:**  NA
> Action Network - SDK adapter

- oauth2/google_bigquery_connector.rb
- Oauth2
- Add rows to table (Streaming data into a table of Google BigQuery)
_______
Original PR link: https://github.com/workato/connector_sdk/pull/88
> Google Bigquery - SDK adapter

- custom_auth/sage_intacct_connector.rb
- custom_auth
_______
_______
**CS-Contact:**  @vivek88
**Issue link:**  https://github.com/workato/issues/issues/5630
> Sage Intacct (custom) - SDK adapter

- css/style.css
- index.html
- js/script.js
Added navigation links
Remove Documentation and Submit Tickets section
Minor UI changes
> Updated UI

- css/style.css
- index.html
- js/script.js
Fix incorrect interface display when screen width is over 1660px
Added no result error message
Remove fade animation
> UI bug fix and update
